In [1]:
import torch

# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    # Get the number of available GPUs
    num_gpus = torch.cuda.device_count()
    print(f"CUDA is available! Found {num_gpus} GPU(s).")

    # Get the name of the current GPU
    current_gpu_index = torch.cuda.current_device()
    gpu_name = torch.cuda.get_device_name(current_gpu_index)
    print(f"Current GPU: {gpu_name} (index {current_gpu_index})")

    # You can also specify a specific GPU to use if you have multiple
    # device = torch.device("cuda:0") # Use the first GPU
    device = torch.device("cuda") # Use the default (first) available GPU

    # Example tensor operations on the GPU
    tensor_gpu = torch.randn(3, 3).to(device)
    print("\nTensor on GPU:")
    print(tensor_gpu)

    # Perform an operation on the GPU tensor
    result_gpu = tensor_gpu * 2
    print("\nResult of operation on GPU tensor:")
    print(result_gpu)

    # Move a tensor from CPU to GPU
    tensor_cpu = torch.ones(2, 2)
    print("\nTensor on CPU:")
    print(tensor_cpu)
    tensor_moved_to_gpu = tensor_cpu.to(device)
    print("\nTensor moved to GPU:")
    print(tensor_moved_to_gpu)

    # Move a tensor back to CPU
    tensor_back_to_cpu = tensor_moved_to_gpu.cpu()
    print("\nTensor moved back to CPU:")
    print(tensor_back_to_cpu)

    # Example of moving a model to the GPU
    import torch.nn as nn
    import torch.nn.functional as F

    class SimpleNet(nn.Module):
        def __init__(self):
            super(SimpleNet, self).__init__()
            self.fc1 = nn.Linear(10, 5)
            self.fc2 = nn.Linear(5, 2)

        def forward(self, x):
            x = F.relu(self.fc1(x))
            x = self.fc2(x)
            return x

    model = SimpleNet()
    print("\nModel on CPU:")
    print(next(model.parameters()).device) # Check device of model parameters

    model.to(device)
    print("\nModel moved to GPU:")
    print(next(model.parameters()).device) # Check device of model parameters after moving

    # Remember to move your data to the GPU as well during training/inference
    input_data = torch.randn(1, 10).to(device)
    output = model(input_data)
    print("\nOutput from model on GPU:")
    print(output)

else:
    print("CUDA is not available. PyTorch will use the CPU.")
    device = torch.device("cpu")

CUDA is available! Found 1 GPU(s).
Current GPU: NVIDIA GeForce RTX 3070 Ti Laptop GPU (index 0)

Tensor on GPU:
tensor([[ 0.4350, -0.3283,  0.6261],
        [-0.0119, -0.9492, -0.5898],
        [ 0.1005, -1.7411,  0.0770]], device='cuda:0')

Result of operation on GPU tensor:
tensor([[ 0.8700, -0.6566,  1.2523],
        [-0.0237, -1.8984, -1.1795],
        [ 0.2011, -3.4822,  0.1541]], device='cuda:0')

Tensor on CPU:
tensor([[1., 1.],
        [1., 1.]])

Tensor moved to GPU:
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

Tensor moved back to CPU:
tensor([[1., 1.],
        [1., 1.]])

Model on CPU:
cpu

Model moved to GPU:
cuda:0

Output from model on GPU:
tensor([[0.3569, 0.1341]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [1]:
!nvidia-smi

Wed Apr 30 22:52:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.42                 Driver Version: 572.42         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8             16W /  150W |     363MiB /   8192MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----